### PR TITLE
Update custom-nodes-list.json

### PR DESCRIPTION
**Pull request by klinter007**
Added node for contact input strings

### CODE REVIEW

**Comment by ltdrdata** [comment]
Since subfolders cannot be cloned, the `__init__.py` must be located at the root of the repository to enable a clonable structure.
Additionally, for custom nodes in the form of git-clone, the repository path should be included in the files.

**Comment by ltdrdata** [comment]
Is it correct to provide it as a single file instead of the git clone method?

In this case, the file would be directly downloaded to the ComfyUI/custom_nodes path, and users cannot check for updates, so they cannot receive support for this feature.

If you are really going to provide it like that, the install_type should be set to `copy` instead of `git-clone`.

**Comment by klinter007** [comment]
I have no idea which is the better option, these are my baby steps in the world of open source and esp. git.

I would like to add more things to it later, more nodes and probably more files with it.

**Comment by ltdrdata** [comment]
Just change this
```
            "files": [
                "https://github.com/klinter007/klinter_nodes/blob/main/concat_klinter.py"
            ],
```
to

```
            "files": [
                "https://github.com/klinter007/klinter_nodes"
            ],
```

**Comment by klinter007** [comment]
ok,
hope i've done it right 8-)

**Pull request merged**
