### PR TITLE
Add ObjectFusion custom nodes

### PR DESCRIPTION
**Pull request by ducido**

### CODE REVIEW

**Comment by ducido** [comment]
This is a node to generate new image that combine 2 objects from different scene.
https://github.com/ducido/ObjectFusion_ComfyUI_nodes

**Comment by ltdrdata** [comment]
Simply including other custom nodes in that way causes conflicts.
In particular, the mere existence of that code interferes with ComfyUI-Manager's collection of the node list.
If you're going to use some features of those custom nodes, at least remove those nodes from `NODE_CLASS_MAPPINGS`.

https://github.com/ltdrdata/ComfyUI-Manager#custom-node-support-guide

**Comment by ducido** [comment]
Thank you for considering, actually I have made some changes with these existing custom nodes to fit with the problem. Moreover, I also change the folder name, the global name in `NODE_CLASS_MAPPINGS` `NODE_DISPLAY_NAME_MAPPINGS` so that it should not cause conflicts. 
e.g. `"Yoloworld_ESAM_Zho": "Yoloworld ESAM"` -> `"Yoloworld_ESAM_Zho": "🔎Custom Yoloworld ESAM"`
Please tell me if there is anything I should consider to not cause conflict. Thank you!

**Comment by ltdrdata** [comment]
Display name is irrelevant. Key name is the important thing.

**Comment by ducido** [comment]
Yeah, sorry for wrong messege, I changed key name as well

**Pull request merged**
