### PR TITLE
Share to esheep

### PR DESCRIPTION
**Pull request by huyunan496**
share workflow and images to www.esheep.com

### CODE REVIEW

**Comment by ltdrdata** [comment]
`ComfyUI-Manager` is a project targeting international users. Including Chinese UI and comments would be inappropriate.
Support for Chinese UI can be facilitated through https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation.

**Comment by huyunan496** [comment]
> `ComfyUI-Manager` is a project targeting international users. Including Chinese UI and comments would be inappropriate. Support for Chinese UI can be facilitated through https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation.



> `ComfyUI-Manager` is a project targeting international users. Including Chinese UI and comments would be inappropriate. Support for Chinese UI can be facilitated through https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation.

I have changed code to English now, please check once

**Comment by ltdrdata** [comment]
There are chinese comments yet. Please, change them.

**Comment by huyunan496** [comment]
> There are chinese comments yet. Please, change them.

I have change all chiness in code，please check is it OK?

**Pull request merged**
