### PR TITLE
Add custom node silveroxides/ComfyUI_bitsandbytes_NF4

### PR DESCRIPTION
**Pull request by silveroxides**
This is a fork of the currently deprecated custom node by comfyanon that adds further functionality and is aimed at replacing the deprecated one.

### CODE REVIEW

**Comment by ltdrdata** [comment]
If you plan to maintain it independently, please change the repository name.

**Comment by silveroxides** [comment]
> If you plan to maintain it independently, please change the repository name.

I am meant to replace the current one. Mine is already in the registry and you can check with comfyanonymous in the discord channel for verification. If you read the README for the other node you will see that it is deprecated so anyone currently using that needs to have their repo origin changed to continue getting updates.

**Comment by ltdrdata** [comment]
If you plan to manage it continuously, it would be better to move to the default channel rather than the dev channel.

And for those who installed the previous comfyanonymous version, it would be good to add a note in the description recommending them to uninstall and reinstall.

**Comment by silveroxides** [comment]
@ltdrdata Now I have changed to correct node list and renamed my repo.

**Pull request merged**
