### PR TITLE
Added Eagleshadow Custom Nodes entry to custom-node-list.json

### PR DESCRIPTION
**Pull request by Shadetail**
Added Eagleshadow Custom Nodes entry to custom-node-list

### CODE REVIEW

**Comment by ltdrdata** [comment]
Why don't you register as Is there a reason for registering through `copy` method instead of using `git-clone` method? Registering through copying does not allow providing update support to users.

**Comment by Shadetail** [comment]
Oh wow thanks! I'm really glad you noticed that.

This is actually my first PR ever. I saw most other recent entries use `copy` so I thought that's what I was supposed to use as well. I didn't know that would prevent providing update support. Maybe this info could be added [to your readme.](https://github.com/ltdrdata/ComfyUI-Manager#how-to-register-your-custom-node-into-comfyui-manager)

I updated the entry so that it uses `git-clone` instead, as the ability to install and update nodes through manager is the main reason for adding entry for my nodes to manager.

**Comment by ltdrdata** [comment]
You need to change 'files' field, too.
Change it to repo url instead of file url.

**Comment by Shadetail** [comment]
Oops! Fixed!

**Pull request merged**
