### PR TITLE
add a new node

### PR DESCRIPTION
**Pull request by MakkiShizu**
add a simple reimgsize node(s) in comfyui

### CODE REVIEW

**Comment by MakkiShizu** [comment]
I don't know where to write about it, so I'll write here)
I'm a beginner and I'm facing some issues. When merging PR, I encountered the problem "All checks have failed." I'm not sure how to troubleshoot this issue. Here are the links for reference:
[PR](https://github.com/MakkiShizu/comfyui_reimgsize/pull/1)
[Actions Log](https://github.com/MakkiShizu/comfyui_reimgsize/actions/runs/10124704864/job/27999340929)

**Comment by ltdrdata** [comment]
> I don't know where to write about it, so I'll write here) I'm a beginner and I'm facing some issues. When merging PR, I encountered the problem "All checks have failed." I'm not sure how to troubleshoot this issue. Here are the links for reference: [PR](https://github.com/MakkiShizu/comfyui_reimgsize/pull/1) [Actions Log](https://github.com/MakkiShizu/comfyui_reimgsize/actions/runs/10124704864/job/27999340929)

Oh, Sorry for that. 
There was some confusion regarding the comfyregistry backend changes and the publishing PR side. 
Please wait a moment.

**Comment by ltdrdata** [comment]
Now comfyregistry is fixed.

**Comment by MakkiShizu** [comment]
> Now comfyregistry is fixed.

Oh,good.
Do I need to do anything (any actions)?

**Comment by ltdrdata** [comment]
image

Just click the `Run workflow` button in Actions>Publish to Comfy registry

**Pull request closed without merging**
