### PR TITLE
Update extension-node-map.json - remove unused Node Maras IT

### PR DESCRIPTION
**Pull request by MaraScott**

### CODE REVIEW

**Comment by ltdrdata** [comment]
It's not manually managed; it's automatically extracted from the repository by the scanner script.

**Comment by MaraScott** [comment]
Hi @ltdrdata , I don't know what you mean.
Am I suppose to do it differently ?

**Comment by ltdrdata** [comment]
> Hi @ltdrdata , I don't know what you mean. Am I suppose to do it differently ?

`extension-node-map.json` is not manually updated, but it is generated by `scanner.py` by scanning all files of repositories registered in `custom-node-list.json` in the following manner.

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#custom-node-support-guide

If the code pattern in your repository disappears, it will be automatically removed the next time the DB is updated.
And there is no benefit to removing those nodes from `extension-node-map.json` unless there is a specific conflict with node names.

**Comment by MaraScott** [comment]
Ooooh, I did not catch that.

thanks

**Comment by gonzalu** [comment]
This is good to know. I came here looking for similar but on the other way. I wanted to know what happens/what I need to do to add my node suit. 

So, I:

- updated an entry in custom-node-list.json
- I tested it in Manager by using local DB (no errors) 
- in Git-Bash (Windows) I did a "git pull" from the Manager directory
- in Git Bash, I ran the ./scan.sh script

Is this all I need to do? I did get a couple of errors/warnings but they did not seem to break ... script completed. 

When should I see the changes in the main DB (not local) ? 

thank you so much for all you do. I appreciate you.

**Comment by MaraScott** [comment]
Have you created a pull request on this repo to submit your node as explained here in the Readme.md? 


How to register your custom node into ComfyUI-Manager

Add an entry to custom-node-list.json located in the root of ComfyUI-Manager and submit a Pull Request.

NOTE: Before submitting the PR after making changes, please check Use local DB and ensure that the extension list loads without any issues in the Install custom nodes dialog. Occasionally, missing or extra commas can lead to JSON syntax errors.

The remaining JSON will be updated through scripts in the future, so you don't need to worry about it.

**Comment by gonzalu** [comment]
Yup, followed the instructions. See my bullet number 3 above where I did the git pull. Maybe it takes a few hours or days to add to remote DB? 

;)

**Comment by ltdrdata** [comment]
I'll merge this when I get back home.
Repo name changing PR requires some additional work on my side.

**Comment by MaraScott** [comment]
Tx

**Comment by gonzalu** [comment]
OK I got it sorted. I was missing a few modules under Python/Pip to run the script ... namely the Github tools ;) 

This time the script ran, it clones all repos in my .tmp folder and looks like it completed without errors. 

Fingers crossed :D 
Thanks guys.

**Comment by ltdrdata** [comment]
> OK I got it sorted. I was missing a few modules under Python/Pip to run the script ... namely the Github tools ;)
> 
> This time the script ran, it clones all repos in my .tmp folder and looks like it completed without errors.
> 
> Fingers crossed :D Thanks guys.

You don't need update it by yourself.
Typically, after I update the custom-node-list.json, I run a script periodically to update it. Especially since the github stat information is also supported, it has become quite a lengthy task.

**Pull request closed without merging**
