### PR TITLE
Update custom-node-list.json

### PR DESCRIPTION
**Pull request by Amorano**
better descriptions for expanding node suite

### CODE REVIEW

**Review by ltdrdata — APPROVED** [review]

**Comment by Amorano** [comment]
Any reason my description was changed by someone other than me?

**Comment by ltdrdata** [comment]
let me check. there must be mistake.

**Comment by ltdrdata** [comment]
Oh.. I'd updated it because of this.
I'll roll back it.
https://github.com/Amorano/Jovimetrix/blob/82d9601327a401102fe1f10ae399adea66525626/__init__.py#L36

**Comment by Amorano** [comment]
OH! Is this a me mistake? Can I just update the description in the header? I tried to follow the exemplar you had, but I was not sure if that was auto-scrapping. I will make sure to keep that header updated. Sorry!

**Comment by ltdrdata** [comment]
> OH! Is this a me mistake? Can I just update the description in the header? I tried to follow the exemplar you had, but I was not sure if that was auto-scrapping. I will make sure to keep that header updated. Sorry!

It's not an auto update. But, I noticed from auto-scrap. And I thought that I have to update it.

**Pull request merged**
