### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Excidos**
Added my custom node

https://github.com/Excidos/ComfyUI-Documents

{
    "author": "Indra's Mirror",
    "title": "ComfyUI-Documents",
    "reference": "https://github.com/Excidos/ComfyUI-Documents",
    "files": [
        "https://github.com/Excidos/ComfyUI-Documents/raw/main/document_nodes.py",
        "https://github.com/Excidos/ComfyUI-Documents/raw/main/utils.py",
        "https://github.com/Excidos/ComfyUI-Documents/raw/main/server.py",
        "https://github.com/Excidos/ComfyUI-Documents/raw/main/comfy_documents_utils.py",
        "https://github.com/Excidos/ComfyUI-Documents/raw/main/web/js/documents.core.js"
    ],
    "install_type": "git-clone",
    "pip": [
        "PyMuPDF",
        "python-docx"
    ],
    "description": "ComfyUI-Documents is a powerful extension for ComfyUI that enhances workflows with advanced document processing capabilities. It includes nodes for loading and parsing various document types (PDF, TXT, DOC, DOCX), converting PDF pages to images, splitting PDFs into individual pages, and selecting specific images from batches. Features include text extraction, image conversion, and seamless integration with existing ComfyUI projects."
}

### CODE REVIEW

**Comment by ltdrdata** [comment]
Like other custom nodes, change the structure to have an `__init__.py` in the root of the repo, so that it can be directly git cloned into `custom_nodes`.

**Comment by Excidos** [comment]
Okay I made it all in the root folder, should work no worries now. Sorry this is my first custom node and really making a repo and doing a pull request.

**Comment by ltdrdata** [comment]
> Okay I made it all in the root folder, should work no worries now. Sorry this is my first custom node and really making a repo and doing a pull request.

And there is one more thing. You have to remove the `__pycache__` dir from the repo. It is an auto-generated directory and it will cause conflicts on the user's side when updating.

**Comment by Excidos** [comment]
Okay done haha I think it should be all good :) Thank you for your patience.

**Comment by ltdrdata** [comment]
Your node is added manually.
I needed to make some corrections to your PR, so I made the changes myself.

**Pull request closed without merging**
