### PR TITLE
add custom node ComfyUI_Qwen2-Audio-7B-Instruct-Int4

### PR DESCRIPTION
**Pull request by IuvenisSapiens**

### CODE REVIEW

**Comment by ltdrdata** [comment]
Why is the transformers package included separately as `transformers.zip` instead of using the one available on PyPI?

**Comment by IuvenisSapiens** [comment]
The code for Qwen2-Audio has been incorporated into the latest version of Hugging Face Transformers **(4.45.0.dev0)**, which is not currently available on PyPI.

It is advised to build from the source using the command `pip install git+https://github.com/huggingface/transformers` to avoid encountering the following error:

`KeyError: 'qwen2-audio'`.

**Comment by ltdrdata** [comment]
> git+https://github.com/huggingface/transformers

It might be better to delete `transformer.zip` and use `git+https://github.com/huggingface/transformers` instead of `transformer.zip` in `requirements.txt`.

Due to recent security issues, we are trying to take an approach that is easily verifiable whenever possible.

**Comment by IuvenisSapiens** [comment]
Thank you for bringing the potential issue with the `transformers.zip` file to our attention and for suggesting an alternative approach. We have reviewed your recommendation and have taken action accordingly.

We have now updated our `requirements.txt` to use the direct Git repository URL `git+https://github.com/huggingface/transformers` instead of the `transformers.zip` file. This change aligns with our commitment to ensuring the security and integrity of our dependencies, and it also allows us to access the latest features and updates from the Hugging Face `Transformers` library.

By using this method, we can avoid potential `KeyError` issues related to the `qwen2-audio` model and ensure that our users have access to the most current and secure version of the library.

Once again, we appreciate your insight and assistance. This adjustment will help us maintain a robust and secure environment for our custom node `ComfyUI_Qwen2-Audio-7B-Instruct-Int4`.

**Pull request merged**
