### PR TITLE
Add custom node for AuraSR

### PR DESCRIPTION
**Pull request by alexisrolland**
Add custom node for AuraSR upscaler.

### CODE REVIEW

**Comment by ltdrdata** [comment]
The registration of this custom node's repository is currently pending due to a name conflict. A repository named ComfyUI-AuraSR already exists. It is recommended to change the repository name.

**Comment by alexisrolland** [comment]
> The registration of this custom node's repository is currently pending due to a name conflict. A repository named ComfyUI-AuraSR already exists. It is recommended to change the repository name.

Thank you for the prompt answer. I didn't find any conflicting node except maybe AuraSR-ComfyUI which name looks similar but reversed: https://github.com/GreenLandisaLie/AuraSR-ComfyUI

Is this the one you are referring to?

Note both repos exist on ComfyUI Registery:
- First repo (mine): https://registry.comfy.org/publishers/alexisrolland/nodes/comfyui-aurasr
- Second repo: https://registry.comfy.org/publishers/greenlandisalie/nodes/aurasr-comfyui

**Comment by ltdrdata** [comment]
https://github.com/AIFSH/ComfyUI-AuraSR

This is the conflicting repo.
Although the two repos were released at almost the same time, unfortunately this repo was a step ahead.

**Comment by alexisrolland** [comment]
Okay, let's close this PR.
Thanks!

**Pull request closed without merging**
