### PR TITLE
Added Dream Project Animation Nodes.

### PR DESCRIPTION
**Pull request by alt-key-project**
Adding the Dream Project Animation Nodes to the custom nodes list.

### CODE REVIEW

**Comment by ltdrdata** [comment]
The `Dream Project Animation` node has already been added. I have updated the description and title separately in the PR.

**Comment by alt-key-project** [comment]
Ok, thank you! I did not know that projects were added automatically.

**Comment by ltdrdata** [comment]
> Ok, thank you! I did not know that projects were added automatically.

I added descriptions and titles manually as I saw fit. :)

**Comment by razvanab** [comment]
Is there a tutorial somewhere on how to use it?

**Pull request closed without merging**
