### PR TITLE
custom node ComfyUX commit

### PR DESCRIPTION
**Pull request by googincheng**
https://github.com/googincheng/ComfyUX

### CODE REVIEW

**Comment by ltdrdata** [comment]
You have to remove `PyComfyNode/__pycache__` dir from repo.

**Comment by WX-NPS1598** [comment]
https://github.com/WX-NPS1598/ComfyUI-auto-crop-by-NPS

**Comment by googincheng** [comment]
> You have to remove `PyComfyNode/__pycache__` dir from repo.

done~

**Comment by WX-NPS1598** [comment]
https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS
sorry,I changed the name of the project to make it easier to search, so I reuploaded it.

**Comment by ltdrdata** [comment]
> https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS sorry,I changed the name of the project to make it easier to search, so I reuploaded it.

Why do you use `simpleeval`?

**Comment by WX-NPS1598** [comment]
> > https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS sorry,I changed the name of the project to make it easier to search, so I reuploaded it.
> 
> Why do you use `simpleeval`?

When I searched for "auto crop" it didn't find my node, I had to search for "auto-crop" so I deleted the original code and created a new one

**Comment by ltdrdata** [comment]
> > > https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS sorry,I changed the name of the project to make it easier to search, so I reuploaded it.
> > 
> > 
> > Why do you use `simpleeval`?
> 
> When I searched for "auto crop" it didn't find my node, I had to search for "auto-crop" so I deleted the original code and created a new one

Nope. I am asking about `requirements.txt`.

**Comment by WX-NPS1598** [comment]
> > > > https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS sorry,I changed the name of the project to make it easier to search, so I reuploaded it.
> > > 
> > > 
> > > Why do you use `simpleeval`?
> > 
> > 
> > When I searched for "auto crop" it didn't find my node, I had to search for "auto-crop" so I deleted the original code and created a new one
> 
> Nope. I am asking about `requirements.txt`.

好的，我检查了一下，确实没有用到“simpleeval”，我刚刚删除了“requirements.txt”，thank you

**Comment by WX-NPS1598** [comment]
> > > > https://github.com/WX-NPS1598/ComfyUI-Auto_Crop_By_NPS sorry,I changed the name of the project to make it easier to search, so I reuploaded it.
> > > 
> > > 
> > > Why do you use `simpleeval`?
> > 
> > 
> > When I searched for "auto crop" it didn't find my node, I had to search for "auto-crop" so I deleted the original code and created a new one
> 
> Nope. I am asking about `requirements.txt`.

Ok, I checked, there is no "simpleeval" used, I just deleted "requirements.txt", thank you.I'm a newbie so I don't understand the rules, sorry

**Pull request merged**
