### PR TITLE
better handling of missing permissions in prestartup

### PR DESCRIPTION
**Pull request by DukeSniper**
Fix for #636

### CODE REVIEW

**Comment by hjcxlp** [comment]
after updating prestartup_script.py, still got this error. pls advise

ERROR: Exception:
Traceback (most recent call last):
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
        ^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
           ^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init
  File "D:\ComfyUI\.ext\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ComfyUI\.ext\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] 目录名称无效。
Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\\ComfyUI\\.ext\\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

**Comment by ltdrdata** [comment]
> after updating prestartup_script.py, still got this error. pls advise
> 
> ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI\.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

It seems that you pip environment isn't valid.
Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze`
What is displayed?

**Comment by Pythonpa** [comment]
> > after updating prestartup_script.py, still got this error. pls advise
> > ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.
> 
> It seems that you pip environment isn't valid. Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze` What is displayed?

Here is the same error,and below is the log:
[SD-Launcher] C:\ComfyUI>C:\ComfyUI\python\python.exe -m pip freeze
ERROR: Exception:
Traceback (most recent call last):
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
  File "C:\ComfyUI\python\lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
  File "C:\ComfyUI\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ComfyUI\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] 目录名称无效。

**Comment by ltdrdata** [comment]
> > > after updating prestartup_script.py, still got this error. pls advise
> > > ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.
> > 
> > 
> > It seems that you pip environment isn't valid. Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze` What is displayed?
> 
> Here is the same error,and below is the log: [SD-Launcher] C:\ComfyUI>C:\ComfyUI\python\python.exe -m pip freeze ERROR: Exception: Traceback (most recent call last): File "C:\ComfyUI\python\lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) File "C:\ComfyUI\python\lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( File "C:\ComfyUI\python\lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( File "C:\ComfyUI\python\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\ComfyUI\python\lib\subprocess.py", line 1456, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, NotADirectoryError: [WinError 267] 目录名称无效。

Definitely your python environment is broken. Reinstall your python. And I strongly recommend venv instead of system python. Or use portable version of ComfyUI.

**Comment by Pythonpa** [comment]
> > 
> > Here is the same error,and below is the log: [SD-Launcher] C:\ComfyUI>C:\ComfyUI\python\python.exe -m pip freeze ERROR: Exception: Traceback (most recent call last): File "C:\ComfyUI\python\lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) File "C:\ComfyUI\python\lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) File "C:\ComfyUI\python\lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( File "C:\ComfyUI\python\lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( File "C:\ComfyUI\python\lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( File "C:\ComfyUI\python\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\ComfyUI\python\lib\subprocess.py", line 1456, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, NotADirectoryError: [WinError 267] 
> 
> Definitely your python environment is broken. Reinstall your python. And I strongly recommend venv instead of system python. Or use portable version of ComfyUI.

Thank you. I have commented out the security check by adding `#security_check` to the `prestartup_script.py`  file, thus temporarily skipping this problem, but I will try to reinstall my python according to your suggestion.

**Comment by ltdrdata** [comment]
> C:\ComfyUI\python\python.exe -m pip freeze

That is meaning less.
if `C:\ComfyUI\python\python.exe -m pip freeze` is causing error.
You cannot use manager feature at all.

**Comment by Pythonpa** [comment]
> > C:\ComfyUI\python\python.exe -m pip freeze
> 
> That is meaning less. 那意思就少了。 if `C:\ComfyUI\python\python.exe -m pip freeze` is causing error. 如果 `C:\ComfyUI\python\python.exe -m pip freeze` 导致错误。 You cannot use manager feature at all. 您根本无法使用管理器功能。

By reinstalling the deployment comfyui virtual environment, the problem was resolved, and it took me several hours to fully install and test run the 70 + nodes I used before.....LOL
I guess one of the reasons for my problem is that I replaced the hard disk and copied the complete ComfyUI directly from disk D to disk C.

**Comment by hjcxlp** [comment]
> > after updating prestartup_script.py, still got this error. pls advise
> > ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.
> 
> It seems that you pip environment isn't valid. Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze` What is displayed?



 pls advise if there are other solutions for this  than reinstalling the python virtual env. Thx.

**Comment by ltdrdata** [comment]
> > > after updating prestartup_script.py, still got this error. pls advise
> > > ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.
> > 
> > 
> > It seems that you pip environment isn't valid. Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze` What is displayed?
> 
> 
> 
> pls advise if there are other solutions for this than reinstalling the python virtual env. Thx.

Honestly speaking, fixing a broken Python environment is beyond my capabilities. I do have a few ideas, but I can't predict what additional issues they might cause. Rather than applying temporary fixes, a complete reinstallation would be much more efficient

**Comment by Pythonpa** [comment]
> > > > after updating prestartup_script.py, still got this error. pls advise
> > > > ERROR: Exception: Traceback (most recent call last): File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\cli\base_command.py", line 180, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\commands\freeze.py", line 98, in run for line in freeze( File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 43, in freeze req = FrozenRequirement.from_dist(dist) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 238, in from_dist req, comments = _get_editable_info(dist) ^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\operations\freeze.py", line 165, in _get_editable_info vcs_backend = vcs.get_backend_for_dir(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir repo_path = vcs_backend.get_repository_root(location) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\git.py", line 501, in get_repository_root r = cls.run_command( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\vcs\versioncontrol.py", line 650, in run_command return call_subprocess( ^^^^^^^^^^^^^^^^ File "D:\ComfyUI.ext\Lib\site-packages\pip_internal\utils\subprocess.py", line 141, in call_subprocess proc = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init File "D:\ComfyUI.ext\Lib\subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\ComfyUI.ext\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NotADirectoryError: [WinError 267] 目录名称无效。 Failed to execute startup-script: D:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\ComfyUI.ext\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.
> > > 
> > > 
> > > It seems that you pip environment isn't valid. Execute this. `D:\ComfyUI\.ext\python.exe -m pip freeze` What is displayed?
> > 
> > 
> > 
> > pls advise if there are other solutions for this than reinstalling the python virtual env. Thx.
> 
> Honestly speaking, fixing a broken Python environment is beyond my capabilities. I do have a few ideas, but I can't predict what additional issues they might cause. Rather than applying temporary fixes, a complete reinstallation would be much more efficient

Yes,I also think this may be the best solution at present.

**Pull request merged**
