### PR TITLE
Adding a "Share" button for people to easily share their ComfyUI art & workflows

### PR DESCRIPTION
**Pull request by thecooltechguy**
Hey! 👋 

I'm building a "Share" button for people to easily share their Comfy art & workflows publicly.

Here's a quick video demo

https://github.com/ltdrdata/ComfyUI-Manager/assets/33400216/4cc791b6-4272-4a75-9c3e-6f76f9627fd7

Would love any feedback! Gonna iron some stuff out and submit this PR for review.

### CODE REVIEW

**Comment by ltdrdata** [comment]
It seems more appropriate to add it as a subfunction of the `Workflow Gallery` button within the Manager Menu, rather than the Main Menu.

Such as this: https://github.com/pythongosssss/ComfyUI-Custom-Scripts

256667228-7b5a3012-4c59-47c6-8eea-85cf534403ea

**Comment by thecooltechguy** [comment]
Hey @ltdrdata 

I just added the ability to choose your sharing destination. So now, users can share to the ComfyUI Matrix server, ComfyWorkflows.com, or both.

To share with the Matrix server, they just need to drop a file called `matrix_accesstoken` with their Matrix access token, in the ComfyUI base folder. This token isn't sent anywhere, and is only used to communicate with Matrix.

I put it in the main menu, since I wanted the "share" operation to be a bit more generalized, and felt it would be more analogous to "Open", "Load", "Save" operations (which are also on the main menu). 

Also, it would make it easier for people to find and use, and hopefully get more people sharing their work with each other!

Would love to hear your thoughts on this, with this new update!

Also, here's a new demo video!

https://github.com/ltdrdata/ComfyUI-Manager/assets/33400216/16826c8e-ffc9-4196-b4e1-48d00c28b36c

**Comment by thecooltechguy** [comment]
Just updated the PR to make it much easier for users to configure their Matrix credentials when sharing (no more messing with access tokens!)

Here's a quick demo of the updated version.

https://github.com/ltdrdata/ComfyUI-Manager/assets/33400216/6faa3632-5cfc-4e3f-a192-699def7f3bcc

@ltdrdata -- would love your thoughts on this & would be cool if we could get this merged! 👀 

Would help a lot of ppl who are often sharing their ComfyUI outputs to the Matrix server :)

**Comment by thecooltechguy** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/assets/33400216/056308e0-bde1-4f3d-9c42-8d4c1cc4d1d3

Just made some updates to add a Comfy setting for hiding/showing the Share button on the main menu, and added a dropdown by the Workflow gallery button for the user to share their art.

@ltdrdata lmk what you think, looking forward to getting this merged!! :D

**Comment by thecooltechguy** [comment]
@ltdrdata just updated the PR so that the user can choose the output image to share.

Screenshot 2023-10-29 at 4 32 06 PM

**Comment by thecooltechguy** [comment]
@ltdrdata Just updated the PR to support the following output types:

- SaveImage
- PreviewImage
- AnimateDiffCombine
- VideoCombine

Also, when uploading to Matrix, a `workflow.json` file will also be uploaded, since I think not many people know that you can just drag/drop Comfy images into ComfyUI to get its workflow. This will make it more explicit and useful (screenshot example below).

Screenshot 2023-11-07 at 11 13 04 AM

Tested all output types to make sure they work, lmk if this looks good! Looking forward to getting this merged! :)

Thanks a lot for your time & help with this!

**Comment by thecooltechguy** [comment]
Updated the PR based on your feedback, it now has 2 columns and a better overall structure. here's a demo video.

https://github.com/ltdrdata/ComfyUI-Manager/assets/33400216/39fb73b8-efd7-4d21-bc61-4ba61d7670bd

**Comment by thecooltechguy** [comment]
@ltdrdata Just updated the PR to make sure that it works with the latest version of the Video Combine node.

**Comment by BaconIsAVeg** [comment]
Not sure why this was needed, but I'm glad to see at least there's a toggle to hide it.

**No one** should be entering their matrix password into a Comfy dialog.  Also not sure why this is in ComfyUI-Manager and not it's own plugin.

**Comment by ltdrdata** [comment]
> Not sure why this was needed, but I'm glad to see at least there's a toggle to hide it.
> 
> **No one** should be entering their matrix password into a Comfy dialog.  Also not sure why this is in ComfyUI-Manager and not it's own plugin.

There is toggle option on settings, already.

**Comment by ltdrdata** [comment]
Currently, this feature is not functioning because the API is broken.

**Pull request merged**
