### PR TITLE
Update custom-node-list.json

### PR DESCRIPTION
**Pull request by noembryo**
Wrong files pulled..

### CODE REVIEW

**Comment by ltdrdata** [comment]
Install type should be changed.
I just modified manually.

**Comment by noembryo** [comment]
I think that the path is still wrong..
Shouldn't be `https://github.com/noembryo/ComfyUI-noEmbryo`?

**Comment by ltdrdata** [comment]
> I think that the path is still wrong.. Shouldn't be `https://github.com/noembryo/ComfyUI-noEmbryo`?

That's right. I am modifying..

**Comment by noembryo** [comment]
Thank you and sorry for the mess..  😳 
It won't happen again (hopefully 😃).

**Pull request closed without merging**
